#!/usr/bin/ruby -Wall
require 'F2_poly.rb'
if ARGV.length < 1
        $stderr.puts "Usage: #{$0} {one or more f2poly strings}"
        exit 1
end
g = F2_poly.new(ARGV[0])
ARGV.shift
puts ARGV.inject(g) {|g, a| g = g.lcm(F2_poly.new(a)) }
