#!/usr/bin/ruby -Wall
require 'Order.rb'

if ARGV.length == 2 or ARGV.length == 3
	m  = F2_poly.new(ARGV[0])
	a  = F2_poly.new(ARGV[1])
	am = F2_poly_mod.new(a, m)
	if ARGV.length == 2
		Order.orbit(am).each{|o| puts o}
	else
		b  = F2_poly.new(ARGV[2])
		bm = F2_poly_mod.new(b, m)
		Order.orbit(am, bm).each{|o| puts o}
	end
else
	$stderr.puts "Usage: #{$0} {modulus} {a} [b for co-orbit]"
	exit 1
end
