#!/usr/bin/ruby -Wall
require 'F2_poly_factor.rb'
count = 1
if ARGV.length == 1
	degree = Integer(ARGV[0])
elsif ARGV.length == 2
	degree = Integer(ARGV[0])
	count  = Integer(ARGV[1])
else
	$stderr.puts "Usage: #{$0} {degree} [count]"
	exit 1
end
(1..count).each{puts F2_poly_factor.random_irr(Integer(degree))}
