#!/usr/bin/ruby -Wall
require 'Int_factor.rb'

do_maximal_proper = false
if ARGV.length >= 1 and ARGV[0] == "-mp"
	do_maximal_proper = true
	ARGV.shift
end
if ARGV.length < 1
	$stderr.puts "Usage: #{$0} [-mp] {one or more integers ...}"
	$stderr.puts "Use -mp to only list maximal proper divisors."
	exit 1
end
ARGV.each do |arg|
	printf "#{arg}:"
	finfo = Int_factor.factor(Integer(arg))
	if do_maximal_proper
		divisors = finfo.maximal_proper_divisors
	else
		divisors = finfo.all_divisors
	end

	divisors.each do |d|
		printf " #{d}"
	end
	printf "\n"
end
