#!/usr/bin/ruby -Wall
require 'Int_mod.rb'
if ARGV.length < 1
	$stderr.puts "Usage: #{$0} {m} {zero or more residues ...}"
	exit 1
end
m = Integer(ARGV[0])
ARGV.shift
sum = Int_mod.new(0, m)
puts ARGV.inject(sum) {|sum, a| sum += Int_mod.new(Integer(a), m)}
