#!/usr/bin/ruby -Wall
require 'Int_mod.rb'

if ARGV.length == 2
	m = Integer(ARGV[0])
	puts -Int_mod.new(Integer(ARGV[1]), m)
elsif ARGV.length == 3
	m = Integer(ARGV[0])
	puts Int_mod.new(Integer(ARGV[1]), m) - Int_mod.new(Integer(ARGV[2]), m)
else
	$stderr.puts "Usage: #{$0} {modulus} {a} {b} or #{$0} {a}"
	exit 1
end
