#!/usr/bin/ruby -Wall
require 'Order.rb'
if ARGV.length < 1
	$stderr.puts "Usage: #{$0} {one or more integers ...}"
	exit 1
end
rv = 0
ARGV.each do |m|
	g = Order.Int_mod_generator(Integer(m))
	if g.nil?
		puts "No generator found."
		rv = 1
	else
		puts g
	end
end
exit rv
