#!/usr/bin/ruby -Wall
require 'Int_mod.rb'

def usage
	$stderr.puts "Usage: #{$0} {-a|-u} {p}"
	exit 1
end

if ARGV.length != 2
	usage
end

do_all = true
if ARGV[0] == "-a"
	do_all = true
elsif ARGV[0] == "-u"
	do_all = false
else
	usage
end
m = Integer(ARGV[1])

if do_all
	Int_mod.elements_for_modulus(m).each{|a| puts a}
else
	Int_mod.units_for_modulus(m).each{|a| puts a}
end
