#!/usr/bin/ruby -Wall
require 'Int_mod.rb'
count = 1
if ARGV.length == 1
	max = Integer(ARGV[0])
elsif ARGV.length == 2
	max = Integer(ARGV[0])
	count = Integer(ARGV[1])
else
	$stderr.puts "Usage: #{$0} {m} [count]"
	exit 1
end
(1..count).each{puts rand(max)}
